server:
  port: ${SERVER_PORT:8080}  # Cấu hình cổng server

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/orderfood
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Cập nhật tự động database schema
    show-sql: true  # Hiển thị SQL query trong log
    properties:
      hibernate:
        id.new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # Sử dụng dialect MySQL
        enable_lazy_load_no_trans: true  # Cho phép tải lazy load ngoài transaction
  main:
    lazy-initialization: true  # Khởi tạo Bean một cách lazy (tăng tốc khởi động ứng dụng)

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html  # Đường dẫn Swagger UI
    operationsSorter: method  # Sắp xếp API theo method
  api-docs:
    path: /api-docs  # Đường dẫn tài liệu OpenAPI
